services:
  - type: web
    name: multimodal-rag-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PDF_URL
        value: https://drive.google.com/file/d/1WP24NxeHs7hlGbP_4s4xDVe9xWzfIOx6/view
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
